openapi: 3.0.0
info:
  title: Gemini API Gateway
  description: 一个将 Gemini API 请求转换为 OpenAI 兼容格式的网关服务
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: 开发服务器

paths:
  /v1/models/{model}:generateContent:
    post:
      summary: 生成内容（非流式）
      description: 接收 Gemini API 格式的请求，转换为 OpenAI 格式并转发
      parameters:
        - name: model
          in: path
          required: true
          schema:
            type: string
          description: 模型名称
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeminiRequest'
      responses:
        '200':
          description: 成功响应
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeminiResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalError'

  /v1/models/{model}:streamGenerateContent:
    post:
      summary: 生成内容（流式）
      description: 接收 Gemini API 流式请求，返回 Server-Sent Events 流
      parameters:
        - name: model
          in: path
          required: true
          schema:
            type: string
          description: 模型名称
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeminiRequest'
      responses:
        '200':
          description: 流式响应
          content:
            text/event-stream:
              schema:
                type: string
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalError'

  /health:
    get:
      summary: 健康检查
      description: 检查服务状态和配置
      responses:
        '200':
          description: 服务正常
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  timestamp:
                    type: string
                    format: date-time
                  uptime:
                    type: number
                    description: 服务运行时间（秒）
                  version:
                    type: string
                    description: 服务版本

components:
  schemas:
    GeminiRequest:
      type: object
      properties:
        contents:
          type: array
          items:
            $ref: '#/components/schemas/Content'
          description: 对话内容
        tools:
          type: array
          items:
            $ref: '#/components/schemas/Tool'
          description: 可用工具
        generationConfig:
          $ref: '#/components/schemas/GenerationConfig'
          description: 生成配置
        safetySettings:
          type: array
          items:
            $ref: '#/components/schemas/SafetySetting'
        systemInstruction:
          oneOf:
            - $ref: '#/components/schemas/Content'
            - type: string
          description: 系统指令
      required:
        - contents

    Content:
      type: object
      properties:
        role:
          type: string
          enum: [user, model]
          description: 消息角色
        parts:
          type: array
          items:
            $ref: '#/components/schemas/Part'
          description: 消息部分
      required:
        - role
        - parts

    Part:
      type: object
      properties:
        text:
          type: string
          description: 文本内容
        functionCall:
          $ref: '#/components/schemas/FunctionCall'
          description: 函数调用
        functionResponse:
          $ref: '#/components/schemas/FunctionResponse'
          description: 函数响应
        inlineData:
          type: object
          properties:
            mimeType:
              type: string
            data:
              type: string
          description: 内联数据
        fileData:
          type: object
          properties:
            mimeType:
              type: string
            fileUri:
              type: string
          description: 文件数据

    Tool:
      type: object
      properties:
        functionDeclarations:
          type: array
          items:
            $ref: '#/components/schemas/FunctionDeclaration'
          description: 函数声明列表

    FunctionDeclaration:
      type: object
      properties:
        name:
          type: string
          description: 函数名称
        description:
          type: string
          description: 函数描述
        parameters:
          type: object
          description: 参数 schema (JSON Schema)

    GenerationConfig:
      type: object
      properties:
        temperature:
          type: number
          minimum: 0
          maximum: 2
          description: 温度参数
        topP:
          type: number
          minimum: 0
          maximum: 1
          description: Top-P 参数
        topK:
          type: integer
          minimum: 0
          description: Top-K 参数
        candidateCount:
          type: integer
          minimum: 1
          maximum: 8
          description: 候选数量
        maxOutputTokens:
          type: integer
          minimum: 1
          description: 最大输出 token 数
        stopSequences:
          type: array
          items:
            type: string
          description: 停止序列

    GeminiResponse:
      type: object
      properties:
        candidates:
          type: array
          items:
            $ref: '#/components/schemas/Candidate'
          description: 生成候选
        usageMetadata:
          $ref: '#/components/schemas/UsageMetadata'
          description: 使用统计
        promptFeedback:
          $ref: '#/components/schemas/PromptFeedback'
          description: 提示反馈

    Candidate:
      type: object
      properties:
        content:
          $ref: '#/components/schemas/Content'
          description: 候选内容
        finishReason:
          type: string
          enum:
            - FINISH_REASON_UNSPECIFIED
            - STOP
            - MAX_TOKENS
            - SAFETY
            - RECITATION
            - OTHER
          description: 完成原因
        index:
          type: integer
          description: 候选索引
        safetyRatings:
          type: array
          items:
            $ref: '#/components/schemas/SafetyRating'

    UsageMetadata:
      type: object
      properties:
        promptTokenCount:
          type: integer
          description: 提示 token 数
        candidatesTokenCount:
          type: integer
          description: 候选 token 数
        totalTokenCount:
          type: integer
          description: 总 token 数

    FunctionCall:
      type: object
      properties:
        name:
          type: string
          description: 函数名称
        args:
          type: object
          description: 函数参数

    FunctionResponse:
      type: object
      properties:
        name:
          type: string
          description: 函数名称
        response:
          type: object
          description: 函数响应

    SafetySetting:
      type: object
      properties:
        category:
          type: string
          description: 安全类别
        threshold:
          type: string
          description: 安全阈值

    SafetyRating:
      type: object
      properties:
        category:
          type: string
          description: 安全类别
        probability:
          type: string
          description: 概率

    PromptFeedback:
      type: object
      properties:
        safetyRatings:
          type: array
          items:
            $ref: '#/components/schemas/SafetyRating'
        blockReason:
          type: string
          description: 阻止原因

  responses:
    BadRequest:
      description: 请求格式错误
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: INVALID_REQUEST
                  message:
                    type: string
                  details:
                    type: object

    Unauthorized:
      description: 认证失败
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: AUTHENTICATION_ERROR
                  message:
                    type: string

    TooManyRequests:
      description: 请求过于频繁
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: RATE_LIMIT_ERROR
                  message:
                    type: string

    InternalError:
      description: 服务器内部错误
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  code:
                    type: string
                    example: INTERNAL_ERROR
                  message:
                    type: string
                  details:
                    type: object

tags:
  - name: Generation
    description: 内容生成接口
  - name: Health
    description: 健康检查接口